### ISSUE TITLE
User should be able to change their profile picture

### ISSUE THREAD

**Issue by kant-github** [kant-github/banter#11]
### Description  
Enable users to update their profile pictures for a personalized experience.  

### Features  
- Upload new profile pictures (JPG, PNG, GIF).  
- Preview before saving.  
- Retain the current picture if changes are canceled.  

### Screenshot  
<img width="505" alt="Screenshot 2024-12-04 at 3 46 04 AM" src="https://github.com/user-attachments/assets/b9498136-be52-4f1b-a2c3-d93ffb7b51d4">

### Tasks  
- [ ] Design UI for picture upload.  
- [ ] Validate and store images.  
- [ ] Replace old picture with the new one upon save.
